# Generated by Django 4.1.1 on 2022-09-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='isBiting',
        ),
    ]
