# Generated by Django 4.1.1 on 2022-09-26 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_remove_dog_isbiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='dashound', max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(default='Black', max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='dog',
            name='isBiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(default='Boglárka', max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
